name: Translation Processing

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

on:
  push:
    branches:
      - books
    paths:
      - 'processing/**.json'

jobs:
  translate:
    runs-on: ubuntu-latest
    env:
      LLM_MODEL: ${{ secrets.LLM_MODEL }}
      LLM_PROMPT: ${{ secrets.LLM_PROMPT }}
      LLM_TOKEN: ${{ secrets.LLM_TOKEN }}
      LLM_URL: ${{ secrets.LLM_URL }}
    steps:
    - name: Checkout books branch
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: books
        path: books-repo

    - name: Checkout pages branch
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: pages
        path: pages-repo

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        cd books-repo
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Get changed files
      id: changed-files
      run: |
        cd books-repo
        # Get files changed in the current commit
        changed_files=$(git diff --name-only HEAD^ HEAD -- processing/*.json)
        if [ -z "$changed_files" ]; then
          echo "No JSON files changed in this commit"
          exit 0
        fi
        echo "Changed files:"
        echo "$changed_files"
        echo "changed_files=${changed_files}" >> $GITHUB_OUTPUT
    
    - name: Process JSON files
      working-directory: books-repo
      run: |
        # Get the list of changed files
        CHANGED_FILES=$(echo "${{ steps.changed-files.outputs.changed_files }}" | tr ' ' '\n')
        
        if [ -z "$CHANGED_FILES" ]; then
          echo "No files to process"
          exit 0
        fi
        
        for file in $CHANGED_FILES; do
          # Verify file exists
          if [ ! -f "$file" ]; then
            echo "File $file not found, skipping"
            continue
          fi
          
          echo "Processing file: $file"
          
          # Process file individually
          set +e
          output=$(python translate.py "$file" 2>&1)
          exit_code=$?
          set -e
          
          if [ $exit_code -eq 0 ]; then
            # Get generated file path from output
            generated_file=$(echo "$output" | grep "Writing output file" | awk -F': ' '{print $2}' | awk '{print $1}')
            
            if [ -z "$generated_file" ]; then
              echo "::error::Could not determine generated file path"
              exit 1
            fi
            
            if [ -f "$generated_file" ]; then
              # Move generated HTML file to pages-repo
              mkdir -p ../pages-repo/$(dirname "$generated_file")
              mv "$generated_file" ../pages-repo/$(dirname "$generated_file")/
              echo "Moved $generated_file to pages-repo"
            else
              echo "::error::Generated file not found: $generated_file"
              exit 1
            fi
            
            # Remove processed JSON file
            git rm "$file"
            echo "Successfully processed $file"
          else
            echo "Error processing $file: ${output}"
            exit $exit_code
          fi
        done

    - name: Configure Git
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        cd books-repo
        git config user.email "actions@github.com"
        git config user.name "GitHub Actions"
        cd ../pages-repo
        git config user.email "actions@github.com"
        git config user.name "GitHub Actions"
                
    - name: Commit changes to books branch
      working-directory: books-repo
      run: |
        if git diff --cached --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Remove processed JSON files" || true
        fi
        
    - name: Commit changes to pages branch
      working-directory: pages-repo
      run: |
        # Add HTML files explicitly
        find . -name '*.html' -exec git add {} +
        
        # Check for staged changes
        if git diff --cached --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Add generated HTML files"
          echo "Changes committed successfully"
        fi
        
        # Verify changes were successfully committed
        if ! git diff --quiet HEAD^ HEAD; then
          echo "Successfully committed changes"
          echo "Committed HTML files:"
          git show --name-only --pretty=format: HEAD
        else
          echo "::error::Failed to commit changes"
          exit 1
        fi

    - name: Push changes to both branches
      run: |
        # Push books branch
        cd books-repo
        git push origin books
        
        # Push pages branch
        cd ../pages-repo
        git push origin pages

    - name: Add workflow prerequisites
      uses: EndBug/add-and-commit@v9
      with:
        add: '.github/workflows/translate.yml'
        message: 'Update translation workflow'
