name: Translation Processing

on:
  push:
    branches:
      - books
    paths:
      - 'processing/**.json'

jobs:
  translate:
    runs-on: ubuntu-latest
    env:
      LLM_MODEL: ${{ secrets.LLM_MODEL }}
      LLM_PROMPT: ${{ secrets.LLM_PROMPT }}
      LLM_TOKEN: ${{ secrets.LLM_TOKEN }}
      LLM_URL: ${{ secrets.LLM_URL }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v41
      with:
        files: |
          processing/**.json
    
    - name: Process files
      run: |
        OUTPUT_PATHS=""
        DELETED_FILES=""
        
        # Get the list of changed files
        CHANGED_FILES=$(echo "${{ steps.changed-files.outputs.all_changed_files }}" | tr ' ' '\n')
        
        for file in $CHANGED_FILES; do
          # Extract filename components using regex
          if [[ "$(basename "$file")" =~ ^([a-zA-Z0-9]+)-([0-9]+)-([0-9]+)\.json$ ]]; then
            source="${BASH_REMATCH[1]}"
            bookid="${BASH_REMATCH[2]}"
            index="${BASH_REMATCH[3]}"
            
            # Pass file to translation script with error handling
            set +e
            output=$(python translate.py "$file" 2>&1)
            exit_code=$?
            set -e
            
            if [ $exit_code -eq 0 ]; then
              read -r -a parts <<< "$output"
              # Check success status
              if [ "${parts[1]}" = "True" ]; then
                echo "Successfully processed $file, output at ${parts[0]}"
                rm "$file"
                DELETED_FILES="$DELETED_FILES $file"
                OUTPUT_PATHS="$OUTPUT_PATHS ${parts[0]}"
              else
                echo "Failed to process $file: ${output}"
              fi
            else
              echo "Error processing $file: ${output}"
              exit $exit_code
            fi
          else
            echo "Skipping $file - filename pattern mismatch"
          fi
        done

    - name: Configure Git
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"

    - name: Add and Commit changes
      run: |
        git add "$OUTPUT_PATHS" "$DELETED_FILES" # Add generated HTML and remove JSON files
        git commit -m "Add translated HTML files and delete processed JSON files" || echo "No changes to commit"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: books
        force: true
