name: Translation Processing

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

on:
  push:
    branches:
      - books
    paths:
      - 'processing/**.json'

jobs:
  translate:
    runs-on: ubuntu-latest
    env:
      LLM_MODEL: ${{ secrets.LLM_MODEL }}
      LLM_PROMPT: ${{ secrets.LLM_PROMPT }}
      LLM_TOKEN: ${{ secrets.LLM_TOKEN }}
      LLM_URL: ${{ secrets.LLM_URL }}
    steps:
    - name: Checkout books branch
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: books
        path: books-repo

    - name: Checkout pages branch
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: pages
        path: pages-repo

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        cd books-repo
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Get changed files
      id: changed-files
      run: |
        cd books-repo
        changed_files=$(find processing -name '*.json')
        echo "changed_files=${changed_files}" >> $GITHUB_OUTPUT
    
    - name: Process JSON files
      working-directory: books-repo
      run: |
        # Get the list of changed files
        CHANGED_FILES=$(echo "${{ steps.changed-files.outputs.all_changed_files }}" | tr ' ' '\n')
        
        for file in $CHANGED_FILES; do
          # Verify file exists
          if [ ! -f "$file" ]; then
            echo "File $file not found, skipping"
            continue
          fi
          
          # Process file individually
          set +e
          output=$(python translate.py "$file" 2>&1)
          exit_code=$?
          set -e
          
          # Move generated HTML file to pages-repo
          generated_file=$(echo "$output" | grep "Writing output file" | awk '{print $1}')
          if [ -f "$generated_file" ]; then
            mv "$generated_file" ../pages-repo/
          fi
          
          if [ $exit_code -eq 0 ]; then
            # Remove processed JSON file
            git rm "$file"
            echo "Successfully processed $file"
          else
            echo "Error processing $file: ${output}"
            exit $exit_code
          fi
        done
        
    - name: Commit changes to books branch
      working-directory: books-repo
      run: |
        if git diff --cached --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Remove processed JSON files" || true
        fi
        
    - name: Commit changes to pages branch
      working-directory: pages-repo
      run: |
        if git diff --cached --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Add generated HTML files" || true
        fi
        
        # Set outputs for subsequent steps
        echo "output_paths=${OUTPUT_PATHS}" >> $GITHUB_OUTPUT
        echo "deleted_files=${DELETED_FILES}" >> $GITHUB_OUTPUT
        
        # Fail if no files were processed
        if [ -z "$OUTPUT_PATHS" ] && [ -z "$DELETED_FILES" ]; then
          echo "::error::No changes to commit - failing workflow"
          exit 1
        fi
        
        # Fail if no files were processed
        if [ -z "$OUTPUT_PATHS" ] && [ -z "$DELETED_FILES" ]; then
          echo "::error::No changes to commit - failing workflow"
          exit 1
        fi

    - name: Configure Git
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        
    - name: Push changes to both branches
      run: |
        # Push books branch
        cd books-repo
        git push origin books
        
        # Push pages branch
        cd ../pages-repo
        git push origin pages

    - name: Add workflow prerequisites
      uses: EndBug/add-and-commit@v9
      with:
        add: '.github/workflows/translate.yml'
        message: 'Update translation workflow'
