name: Translation Processing

on:
  push:
    paths:
      - 'processing/**'

jobs:
  translate:
    runs-on: ubuntu-latest
    env:
      LLM_MODEL: ${{ secrets.LLM_MODEL }}
      LLM_PROMPT: ${{ secrets.LLM_PROMPT }}
      LLM_TOKEN: ${{ secrets.LLM_TOKEN }}
      LLM_URL: ${{ secrets.LLM_URL }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Process files
      run: |
        for file in processing/*; do
          if [ -f "$file" ]; then
            python translate.py "$file"
            if [ $? -eq 0 ]; then
              echo "Successfully processed $file"
              rm "$file"  # Remove processed file
            else
              echo "Failed to process $file"
            fi
          fi
        done
    