name: Translation Processing

on:
  push:
    branches:
      - books
    paths:
      - 'processing/**'

jobs:
  translate:
    runs-on: ubuntu-latest
    env:
      LLM_MODEL: ${{ secrets.LLM_MODEL }}
      LLM_PROMPT: ${{ secrets.LLM_PROMPT }}
      LLM_TOKEN: ${{ secrets.LLM_TOKEN }}
      LLM_URL: ${{ secrets.LLM_URL }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Process files
      run: |
        OUTPUT_PATHS=""
        DELETED_FILES="" # Initialize variable to track deleted files
        for file in processing/*; do
          if [ -f "$file" ]; then
            output=$(python translate.py "$file")
            read output_path success <<< "$output"
            if [ "$$success" == "True" ]; then
              echo "Successfully processed $file, output at $output_path"
              rm "$file" # Remove local file after successful processing
              DELETED_FILES="$DELETED_FILES $file" # Track file for deletion from repo
              OUTPUT_PATHS="$OUTPUT_PATHS $$output_path" # Append output path to list
            else
              echo "Failed to process $file"
            fi
          fi
        done

    - name: Configure Git
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"

    - name: Add and Commit changes
      run: |
        git add $$OUTPUT_PATHS $$DELETED_FILES # Add generated HTML and remove JSON files
        git commit -m "Add translated HTML files and delete processed JSON files" || echo "No changes to commit"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: books
        force: true

    # - name: Delete processed JSON file # Removed separate delete step
    #   run: |
    #     git rm "$file"
    #     git commit -m "Delete processed JSON file" || echo "No changes to commit"
    #     git push origin books
